services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_PATH: data/fitnessapp.db
      GARMIN_EMAIL: ${GARMIN_EMAIL}
      GARMIN_PASSWORD: ${GARMIN_PASSWORD}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    volumes:
      - backend_data:/app/data

volumes:
  backend_data:
